### ISSUE TITLE
[rockylinux-8] python3 incompatible with latest ansible

### ISSUE THREAD

**Issue by wookietreiber** [hspaans/molecule-containers#470]
```console
$ docker run --rm -it ghcr.io/hspaans/molecule-containers:rockylinux-8 python3 --version
Python 3.6.8
```

This get's installed with the GitHub action: 

> Successfully installed Jinja2-3.1.5 MarkupSafe-3.0.2 PyYAML-6.0.2 ***ansible-11.2.0*** ansible-compat-25.1.1 ***ansible-core-2.18.2*** attrs-25.1.0 bracex-2.5.post1 certifi-2024.12.14 cffi-1.17.1 charset-normalizer-3.4.1 click-8.1.8 click-help-colors-0.9.4 cryptography-44.0.0 distro-1.9.0 docker-7.1.0 enrich-1.2.7 idna-3.10 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 markdown-it-py-3.0.0 mdurl-0.1.2 molecule-25.2.0 molecule-plugins-23.7.0 packaging-24.2 pluggy-1.5.0 pycparser-2.22 pygments-2.19.1 referencing-0.36.2 requests-2.32.3 resolvelib-1.0.1 rich-13.9.4 rpds-py-0.22.3 selinux-0.3.0 subprocess-tee-0.4.2 typing-extensions-4.12.2 urllib3-2.3.0 wcmatch-10.0

The error I'm getting is: 

```
SyntaxError: future feature annotations is not defined
```

I think the python version shipping with the container is too old for the latest ansible version. From checking `dnf search python3` the latest python version that can be installed is `dnf install python3.12`, molecule can then be configured to use `/usr/bin/python3.12` if not detected automatically.

**Comment by wookietreiber** [comment]
Well, this is to be expected now, since Ansible team decided to bump the requirements of the target host, see [here](https://docs.ansible.com/ansible-core/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) for comparison.

I have now started to lock-in the supported Ansible versions in my workflow matrix, e.g.:

```yml
      matrix:
        distro:
          - name: rockylinux-8
            ansible: 2.16 # latest to support target python 3.6
          - name: rockylinux-9
            ansible: 2.18
        scenario:
          - default
          - alternative
```
