### ISSUE TITLE
[rockylinux-8/9] sudo is missing for become tasks

### ISSUE THREAD

**Issue by wookietreiber** [hspaans/molecule-containers#471]
For tasks which have `become: yes`:

> fatal: [rocky-9]: FAILED! => {"attempts": 10, "changed": false, "module_stderr": "/bin/sh: line 1: sudo: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 127}

**Comment by wookietreiber** [comment]
**Workaround:**

```yml
platforms:

  - name: rockylinux-8
    image: ghcr.io/hspaans/molecule-containers:rockylinux-8
    groups:
      - rockylinux

  - name: rockylinux-9
    image: ghcr.io/hspaans/molecule-containers:rockylinux-9
    groups:
      - rockylinux

provisioner:
  name: ansible
  inventory:
    group_vars:
      rockylinux:
        ansible_become_method: su
```

**Comment by hspaans** [comment]
The images are there as clean and non-configured images as it otherwise would assume a certain state not delivered out of the box as other privilege escalation tools can also be installed. With the prepare step in `prepare.yml` as shown below should help (not tested).

```
---
- name: Prepare
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (on Redhat).
      yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Install packages
      package:
        name: sudo
        state: present
```
